
sys-core:
  db:
    name: "getcouragenow.db"
    encryptKey: "testkey!@"
    rotationDuration: 1 # days
    dbDir: "./db"
  cron:
    # Refer here to write rules: https://godoc.org/github.com/robfig/cron
    backupSchedule: "@daily" # @daily - Every day, @hourly - Every hour, @every 1h30m - Every hour thirty.
    rotateSchedule: "@every 24h"
    backupDir: "./db/backups"