sys-account:
  unauthenticatedRoutes:
    - /v2.services.AuthService/Login
    - /v2.services.AuthService/Register
    - /v2.services.AuthService/ResetPassword
    - /v2.services.AuthService/ForgotPassword
    - /v2.services.AuthService/RefreshAccessToken
    - /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo
  jwt:
    access:
      expiry: 3600
    refresh:
      expiry: 3600